import { Box, Button, Card, CardActionArea, CardContent, CardHeader, Typography } from '@mui/material'
import Link from "next/link"
import Head from 'next/head'
import useSWRInfinite from 'swr/infinite'
import { User } from '@prisma/client'

export async function getServerSideProps() {
  return {
    redirect: {
      destination: "/profile",
      permanent: true
    }
  }
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Hive</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Typography>Hive</Typography>
    </>
  )
}
