import { Box, Card, CardActionArea, CardContent, CardHeader, Typography } from '@mui/material'
import Link from "next/link"
import Head from 'next/head'
import { testUsers } from '@/lib/data'
import prisma from '@/lib/prisma'
import { InferGetServerSidePropsType } from 'next'

export async function getServerSideProps() {
  const students = await prisma.student.findMany({
    include: {
      group: true
    },
    orderBy: {
      stingGroupId: "asc"
    }
  });

  return {
    props: {
      students
    }
  }
}

export default function Home({ students }: InferGetServerSidePropsType<typeof getServerSideProps>) {
  return (
    <>
      <Head>
        <title>Hive</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {students.length > 0 ? students.map((t, i) => (
          <Link key={i} href={`/sting/${t.stingGroupId}`}>
            <Card sx={{ mb: 3 }}>
              <CardContent sx={{ display: "flex" }}>
                <Box flex="1">
                  <Typography>{t.name}</Typography>
                </Box>
                <Box flex="1">
                  <Typography>Sting Group {t.stingGroupId}</Typography>
                </Box>
              </CardContent>
            </Card>
          </Link>
        )) : <Typography>Nothing found here...</Typography>}
      </main>
    </>
  )
}
